zeepy/utilities/api.py

Some z/OS systems require this header to be set on all requests made to the z/OSMF REST API.

Specify X-CSRF-ZOSMF-HEADER header for REST requests

---

README.md
requirements.txt
zeepy/utilities/__init__.py
zeepy/utilities/constants.py
zeepy/utilities/exceptions.py
zeepy/utilities/zosmf_profile.py
zeepy/zeepy.py

This makes it possible to instantiate the Zeepy class using a z/OSMF profile created in Zowe CLI or Zowe Explorer, rather than needing hardcoded connection details.
Both plain text and secure profiles are supported on Windows. On Linux only plain text profiles are supported because of [this issue](https://github.com/jaraco/keyring/issues/402).

Support loading z/OSMF connection details from profiles

---

README.md
zowe_sdk/utilities/zosmf_profile.py

Works around [this issue](https://github.com/jaraco/keyring/issues/402) by looking for "account" instead of "username" field (to be compatible with how Keytar and Zowe SCS store credentials).
Given that there seem to be some platform-specific oddities around how credentials are stored, updated the disclaimer in the README stating that secure credential support has only been tested in Windows and Ubuntu. It has not yet been tested on macOS or other Linux distros.

Enable loading secure credentials on Linux

---

.github/workflows/dev-release.yaml

Initially I set up the Release workflow to run on all pushes to the "next" branch that modify the "src" folder. The creation of a new GitHub release every time a PR is merged into the "next" branch may be undesirable. I do not want to spam our release history 🙂 
In this PR, the behavior is changed to only publish dev releases for PRs merged into the "next" branch with the "release-dev" label.

Only publish dev releases for labelled PRs

---

src/core/zowe/core_for_zowe_sdk/request_handler.py
src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
tests/unit/test_zos_console.py
tests/unit/test_zos_files.py
tests/unit/test_zos_jobs.py
tests/unit/test_zos_tso.py
tests/unit/test_zosmf.py
tests/unit/test_zowe_core.py

* Fix error when "Content-Type" header missing from response
* Remove unnecessary calls to `json.dumps`
* Fix "https://" protocol duplicated in unit tests

Fix minor stuff observed in peer review

---

.github/workflows/dev-release.yaml
README.md

Since running `pip install` from a GitHub release seems to no longer work, and some folks have expressed interest in doing an offline install from wheels, this PR creates a zip bundle in the release workflow 😛 This bundle is structured identically to the Python SDK bundle that is published on zowe.org.

Create zip bundle for GitHub release

---

src/core/zowe/core_for_zowe_sdk/__init__.py
src/core/zowe/core_for_zowe_sdk/config_file.py
src/core/zowe/core_for_zowe_sdk/custom_warnings.py
src/core/zowe/core_for_zowe_sdk/exceptions.py
src/core/zowe/core_for_zowe_sdk/profile_constants.py
src/core/zowe/core_for_zowe_sdk/profile_manager.py
src/core/zowe/core_for_zowe_sdk/session.py
tests/unit/fixtures/zowe.config.json
tests/unit/fixtures/zowe.config.user.json
tests/unit/test_zowe_core.py

Now the Profile Manager class has been split into two parts :
- Config File : This just concerns itself with just one file. It handles all the auto-discovering and loading of profiles (prepopulated form base profile properties or just the profile properties). It always raises exceptions when it faces any.
- ProfileManager : This class contains the logic to merge the different properties of profiles (from the Project Config and the Project User Config as well as the Global Config and Global User Config). This class handles all the exceptions raised in the Config File to provide a smooth user experience.
Config File is recommended when the user wants to load just one file while ProfileManager automates the merging of profiles.
This is the duplicate of #113 since I had to rebase against the …

Refactored Profile Manager Class

---

src/zos_console/zowe/zos_console_for_zowe_sdk/console.py
tests/integration/test_zos_console.py
tests/unit/test_zos_console.py

Added a method to call the z/OSMF REST API `GET /zosmf/restconsoles/consoles/<console-name>/solmsgs/C<key-number>`
Signed-off-by: Aaditya Sinha [aadityasinha009@gmail.com](mailto:aadityasinha009@gmail.com)
Resolves #78

[zos-console] Added method to get a command response

---

src/core/setup.py

Broken docs in "next" branch: https://zowe-client-python-sdk.readthedocs.io/en/next/classes/zos_jobs/jobs.html
Fixed docs for this PR: https://zowe-client-python-sdk--146.org.readthedocs.build/en/146/classes/zos_jobs/jobs.html

Fix missing commentjson dependency for core SDK

---

.github/workflows/sdk-build.yml

Codecov was uploading coverage info for every OS and Python version which seems a bit excessive 😋 
Sometimes this was causing the build to fail.
This PR reduces the Codecov check to run only once per OS.

Reduce duplication of Codecov uploads

---

CHANGELOG.md
src/core/zowe/core_for_zowe_sdk/sdk_api.py
src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
tests/unit/test_zos_files.py
tests/unit/test_zos_jobs.py
tests/unit/test_zowe_core.py

fix for #211 
Test all the functions, related to work with datasets and members with '#' character in their names

GH-211 Fixed issue for datasets with '#' in URL

---

CHANGELOG.md
src/core/zowe/core_for_zowe_sdk/session.py

Fixed exception handling in session.py

---

CHANGELOG.md
requirements.txt
src/core/zowe/core_for_zowe_sdk/config_file.py
src/core/zowe/core_for_zowe_sdk/credential_manager.py
src/core/zowe/core_for_zowe_sdk/profile_manager.py
src/core/zowe/core_for_zowe_sdk/validators.py
tests/unit/fixtures/invalid.zowe.config.json
tests/unit/fixtures/invalidUri.zowe.config.json
tests/unit/fixtures/invalidUri.zowe.schema.json
tests/unit/test_zowe_core.py

Validate that zowe.config.json file matches schema

---

CHANGELOG.md
src/core/zowe/core_for_zowe_sdk/config_file.py
src/core/zowe/core_for_zowe_sdk/credential_manager.py
src/core/zowe/core_for_zowe_sdk/profile_manager.py
tests/unit/test_zowe_core.py

Save Profile Properties to Config File & Secure Vault Storage (#73, #72)

---

CHANGELOG.md
requirements.txt
src/core/zowe/core_for_zowe_sdk/config_file.py
src/core/zowe/core_for_zowe_sdk/profile_manager.py
tests/unit/test_zowe_core.py

Fixes profile merge order to match Node.js SDK

---

.github/workflows/sdk-release.yaml
.github/workflows/secrets-sdk.yml
CHANGELOG.md
release.config.js
src/_version.py
src/secrets/Cargo.lock
src/secrets/Cargo.toml

Fix the release workflow - on this branch it successfully published packages to PyPI except for the Secrets SDK which we can trigger with `workflow_dispatch` after this PR is merged 🙂

Update release workflow

---

.github/workflows/sdk-release.yaml
.github/workflows/secrets-sdk.yml

* Updates Octorelease ref to `v1` since the branch ref will stop working after https://github.com/zowe-actions/octorelease/pull/122 is merged
* Don't change directory to release Secrets SDK wheels with `maturin-action`

Update release workflow #2

---

CHANGELOG.md
src/secrets/Cargo.lock
src/secrets/Cargo.toml
src/secrets/README.md
src/secrets/pyproject.toml

- Resolves issues w/ Linux library dependencies
- Adds a repo link and README to Secrets package

secrets: Resolve Linux library dep. issues; add repo and README

---

CHANGELOG.md
src/zos_console/zowe/zos_console_for_zowe_sdk/console.py
tests/unit/test_zos_console.py

GH-231 Now 'issue_command' can use custom console name

---

README.md
src/core/setup.py
src/setup.py
src/zos_console/setup.py
src/zos_files/setup.py
src/zos_jobs/setup.py
src/zos_tso/setup.py
src/zosmf/setup.py

Merge after #232 and before Zowe 2.13 code freeze

Lock down deps and add readmes to package metadata

---

README.md

Update pip install commands to document how to install the latest pre-release version:
* `--pre` will allow prerelease versions to be installed
* `-U` will update if an older version is already installed

Update pip install commands in README.md

---

CHANGELOG.md
src/core/zowe/core_for_zowe_sdk/request_handler.py

- enables use of iterator
- https://requests.readthedocs.io/en/latest/user/quickstart/#raw-response-content
- Download dataset via stream
```python
response = zosmf_files.get_dsn_content_streamed(dsn)
with open(destination_path, "wb") as fd:
for chunk in response.iter_content(chunk_size=256):
fd.write(chunk)
size += len(chunk)
```

return response instead of raw for stream requests

---

.vscode/extensions.json
.vscode/settings.json
CHANGELOG.md
src/core/zowe/core_for_zowe_sdk/config_file.py
src/core/zowe/core_for_zowe_sdk/profile_manager.py
src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
src/zos_tso/zowe/zos_tso_for_zowe_sdk/tso.py
tests/integration/fixtures/files.json
tests/integration/test_zos_console.py
tests/integration/test_zos_files.py
tests/integration/test_zos_jobs.py
tests/integration/test_zos_tso.py
tests/integration/test_zosmf.py
tests/unit/test_zos_files.py
tests/unit/test_zowe_core.py

Fixes several issues with upload/download methods and adds integration tests to verify that they work
Create a team config file in the repo and run integration tests with `pytest tests/integration`

Fix upload file to USS and integration tests

---

.github/workflows/auto-comment.yml
.github/workflows/changelog.yml
.github/workflows/sdk-build.yml
.github/workflows/sdk-release.yaml
.github/workflows/secrets-sdk.yml
.github/workflows/stale.yml

Updates workflows to use non-deprecated Node 20 versions

Update workflows to use Node 20

---

docs/requirements.txt
docs/source/usage/examples.rst
docs/source/usage/installation.rst

See the updated docs here: https://zowe-client-python-sdk--254.org.readthedocs.build/en/254/usage/installation.html
Also updates the PyEnchant dev dep to support M1 Macs so that I could build the docs from source 😋

Update installation docs for prerelease

---

CHANGELOG.md
release.config.js

Recent releases have tags created, but are missing a GitHub release:

Fix missing GitHub releases

---

CHANGELOG.md
src/zos_tso/zowe/zos_tso_for_zowe_sdk/tso.py
tests/integration/test_zos_tso.py
tests/unit/test_zos_tso.py

Fixes #255 and updates the system test for `Tso.issue_command` to verify that the response is successful

Fix error when issuing TSO commands

---

CHANGELOG.md
samples/SampleFiles.py
src/core/zowe/core_for_zowe_sdk/request_handler.py
src/core/zowe/core_for_zowe_sdk/zosmf_profile.py
src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
tests/integration/test_zos_files.py
tests/unit/core/test_request_handler.py

Standardize response

---

CHANGELOG.md
README.md
docs/source/usage/installation.rst
src/setup.py

Renames the python SDK bundle. Addresses [#286]

Rename Python SDK Bundle

---

tests/integration/test_zos_console.py
tests/integration/test_zos_files.py
tests/integration/test_zos_jobs.py
tests/integration/test_zos_tso.py
tests/integration/test_zosmf.py
tests/unit/core/test_sdk_api.py

Updated tests to use context managers

---

CHANGELOG.md
src/core/zowe/core_for_zowe_sdk/sdk_api.py

Fixed a bug on `_create_custom_request_arguments` where changes on `custom_args` will stay after the function returns [#299]

Fixes `_create_custom_request_arguments`

---

CHANGELOG.md
src/core/zowe/core_for_zowe_sdk/sdk_api.py
src/core/zowe/core_for_zowe_sdk/session.py
tests/unit/core/test_sdk_api.py

Supports for `AUTH_TYPE_CERT_PEM` and `AUTH_TYPE_NONE` in `session` addressed in [#291] and [#296]

Support AUTH_TYPE_CERT_PEM and AUTH_TYPE_NONE

---

CHANGELOG.md
src/core/zowe/core_for_zowe_sdk/logger.py
tests/unit/core/test_logger.py
tests/unit/core/test_profile_manager.py
tests/unit/core/test_sdk_api.py

Fixes the bug the logger config would affect other Python application logger [#314].

Fix logger config

---

.github/workflows/sdk-build.yml
.vscode/settings.json
CHANGELOG.md
CONTRIBUTING.md
requirements.txt
src/core/zowe/core_for_zowe_sdk/config_file.py
src/core/zowe/core_for_zowe_sdk/connection.py
src/core/zowe/core_for_zowe_sdk/credential_manager.py
src/core/zowe/core_for_zowe_sdk/logger.py
src/core/zowe/core_for_zowe_sdk/profile_manager.py
src/core/zowe/core_for_zowe_sdk/request_handler.py
src/core/zowe/core_for_zowe_sdk/sdk_api.py
src/core/zowe/core_for_zowe_sdk/session.py
src/core/zowe/core_for_zowe_sdk/zosmf_profile.py
src/zos_files/zowe/zos_files_for_zowe_sdk/datasets.py
src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
tests/integration/test_zos_files.py
tests/unit/core/test_logger.py
tests/unit/files/file_systems/test_file_systems.py

Addresses [#315] by employing pylint for function name checks.

Function case

---

.github/workflows/sdk-build.yml
CHANGELOG.md
scripts/license_header.py
src/_version.py
src/core/setup.py
src/core/zowe/core_for_zowe_sdk/__init__.py
src/core/zowe/core_for_zowe_sdk/config_file.py
src/core/zowe/core_for_zowe_sdk/custom_warnings.py
src/core/zowe/core_for_zowe_sdk/logger.py
src/secrets/zowe/secrets_for_zowe_sdk/__init__.py
src/setup.py
src/zos_console/setup.py
src/zos_console/zowe/zos_console_for_zowe_sdk/__init__.py
src/zos_console/zowe/zos_console_for_zowe_sdk/console.py
src/zos_files/setup.py
src/zos_files/zowe/zos_files_for_zowe_sdk/__init__.py
src/zos_jobs/setup.py
src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/__init__.py
src/zos_tso/setup.py
src/zos_tso/zowe/zos_tso_for_zowe_sdk/__init__.py
src/zosmf/setup.py
src/zosmf/zowe/zosmf_for_zowe_sdk/__init__.py
src/zosmf/zowe/zosmf_for_zowe_sdk/zosmf.py

Adds license header for files and updates workflow with auto check and addition for license headers. [#293]

Add license header

---

.github/workflows/audit.yml
CHANGELOG.md
scripts/license_header.py
src/core/setup.py

Add pip audit workflow

---

.github/workflows/audit.yml
.github/workflows/sdk-release.yaml
requirements.txt
src/secrets/Cargo.lock
src/secrets/Cargo.toml

* Adds cargo audit for Secrets SDK
* Reverts Secrets SDK version to last published one
* Updates `pytest` dev dep for technical currency

Fix audit workflow and revert Secrets SDK version

---

src/secrets/Cargo.lock

Updates the `futures-util` crate since all versions prior to [v0.3.31](https://github.com/rust-lang/futures-rs/releases/tag/0.3.31) were yanked.

Update futures-util crate in Secrets SDK

---

CHANGELOG.md
README.md
samples/SampleFiles.py
tests/integration/test_zos_files.py

Updated sample scripts in readme to stop using deprecated methods
Fixes #336

Sample scripts

---

docs/source/usage/advanced.rst
docs/source/usage/examples.rst
docs/source/usage/getting-started.rst
docs/source/usage/installation.rst
docs/source/usage/requirements.rst

Updates to the documentation's **Getting started** section, including edits for UX and new content for thoroughness.

Anax advanced usage
