- .gitignore
- README.md
- docs/source/conf.py
- src/core/setup.py
- src/core/zowe/core_for_zowe_sdk/sdk_api.py
- src/setup.py
- src/zos_files/setup.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
- src/zos_jobs/setup.py
- src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
Latest release with basic changes:
- Fixed z/OSMF X-CSRF-ZOSMF-HEADER Header issue (PR #19 contribution from @sosadchuk and @ToineMichielseBroadcom)
- Updated release number
- Updated copyright year
> Release 0.2.0

- src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
- changed docstring to reflect real default value used
- changed obtaining user from ApiConnection class via correct attribute
Signed-off-by: Sergei Osadchuk <sergei.osadchuk@broadcom.com>
> list_jobs() owner default value fix

- src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
> feat: added write_to_uss and upload_file_to_uss methods

- src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
Signed-off-by: Richard Gregory <richardgrecoson@gmail.com>
> [zos-files] Add method to delete data set

- src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
Added a method to `cancel` z/OS job
Signed-off-by: Aaditya Sinha <aadityasinha009@gmail.com>
Resolves #56
> [zos-jobs] Added a method to cancel z/OS job

- .codecov.yml
- .github/workflows/sdk-build.yml
- CONTRIBUTING.md
- docs/source/index.rst
Fixes #39 #51
Signed-off-by: Richard Gregory <richardgrecoson@gmail.com>
> Set up automated coverage check and document cmd to run unit tests

- src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
- tests/unit/test_zos_files.py
Signed-off-by: Anton Delchev <dlchv.mail@gmail.com>
> Added rename_dataset and rename_dataset_member methods.

- src/README.md
- src/core/README.md
- src/zos_console/README.md
- src/zos_files/README.md
- src/zos_jobs/README.md
- src/zos_tso/README.md
- src/zosmf/README.md
Added README.md file to src, core, zos_console, zos_files, zos_jobs, zos_tso, zosmf. Related to #79 
Signed-off-by: Anton Delchev <dlchv.mail@gmail.com>
> Added readme files.

- src/zos_files/zowe/zos_files_for_zowe_sdk/constants.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/exceptions.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
- tests/unit/test_zos_files.py
Added parameterized tests for the create_default_dataset method and refactored the method.
Related to #88 
Signed-off-by: Anton Delchev <dlchv.mail@gmail.com>
> Added tests for the create_default_dataset method.

- src/_version.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
- tests/unit/test_zos_files.py
Signed-off-by: Anton Delchev <dlchv.mail@gmail.com>
> Added method to migrate data set.

- src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
- tests/unit/test_zos_jobs.py
Added modify_version optional parameter to the cancel_job method. Related to #90
> Added modify_version to cancel_job method

- src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
- tests/unit/test_zos_files.py
Added method to recall migrated data set. Related to #66
> Added method to recall migrated data set.

- .github/workflows/dev-release.yaml
Signed-off-by: Timothy Johnson <timothy.johnson@broadcom.com>
> Fix release workflow to commit to the right branch

- .github/workflows/dev-release.yaml
- README.md
Signed-off-by: Timothy Johnson <timothy.johnson@broadcom.com>
> Don't use platform specific pyyaml package in bundle

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/label-actions.yml
- .github/workflows/auto-comment.yml
- .github/workflows/changelog.yml
- .github/workflows/stale.yml
- CHANGELOG.md
Action | Description
-- | --
#1 | add [stale bot](https://github.com/zowe/zowe-cli/blob/master/.github/workflows/stale.yml)	
#2 | add [auto-comment](https://github.com/zowe/zowe-cli/blob/master/.github/workflows/auto-comment.yml) bot [on labels](https://github.com/zowe/zowe-cli/blob/master/.github/label-actions.yml)										
#3 | add issue template ([Bug](https://github.com/zowe/zowe-cli/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), [Feature](https://github.com/zowe/zowe-cli/blob/master/.github/ISSUE_TEMPLATE/feature_request.md))										
#4 | add [PR Template ](https://docs.google.com/document/u/0/d/1BvA8zNQs6QP1_gHJw7XsbEGNTTCH-v0SjM4kwMym3Cw/edit)   										
#5 | add [question redirect](https://github.com/zowe/zowe-cli/blob/master/.github/ISSUE_TEMPLATE/config.yml)
> updating workflows - master

- .github/workflows/dev-release.yaml
- .github/workflows/sdk-build.yml
Action | Description
-- | --									
#6 | [update all workflows to remove deprecation warnings](https://github.com/zowe/zowe-cli-web-help-generator/pull/35/files), [octorelease updates](https://github.com/zowe/zowe-cli/pull/1712)
> update workflows - next

- .github/workflows/sdk-build.yml
- requirements.txt
New PR 
Updated PyYAML version `6.0.1`
Changed in sdk.yaml added `pip install -r requirements.txt`
> Add matrix to build workflow #199

- README.md
- docs/requirements.txt
- requirements.txt
- src/setup.py
This PR adds set-up instructions to the Python SDK for developers.
> chore: Update README with developer setup steps

- CHANGELOG.md
- src/core/zowe/core_for_zowe_sdk/config_file.py
- src/core/zowe/core_for_zowe_sdk/profile_manager.py
- tests/unit/test_zowe_core.py
> Load profile properties from env variables

- requirements.txt
added "black" to requirements.txt
Resolved #215 
> added "black" to requirements.txt 

- .github/workflows/sdk-release.yaml
> Fix git checkout step in release workflow

- .github/workflows/sdk-release.yaml
> Don't persist credentials from git checkout

- .github/workflows/sdk-release.yaml
> Don't use fetch-tags on checkout - it doesn't work

- CHANGELOG.md
- src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
- tests/unit/test_zos_files.py
fix for #240 
- [ x ] tested my changes
- [ x ] added/updated automated tests
- [ x ] updated the changelog
- [ x ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)
> #240 create data set accept fba,fbm,vba,vbm

- src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
> Update docstring to specify return type as Json object

- CHANGELOG.md
- src/core/zowe/core_for_zowe_sdk/zosmf_profile.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/__init__.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/datasets.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
- tests/unit/files/datasets/test_create.py
Refactor function `create` definitions in Datasets class to avoid dictionaries as parameters.
> Refactor function definitions

- CHANGELOG.md
- src/core/zowe/core_for_zowe_sdk/config_file.py
- src/core/zowe/core_for_zowe_sdk/connection.py
- src/core/zowe/core_for_zowe_sdk/credential_manager.py
- src/core/zowe/core_for_zowe_sdk/logger.py
- src/core/zowe/core_for_zowe_sdk/profile_manager.py
- src/core/zowe/core_for_zowe_sdk/session.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/datasets.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/file_system.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
- src/zos_files/zowe/zos_files_for_zowe_sdk/uss.py
- src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
- src/zos_tso/zowe/zos_tso_for_zowe_sdk/tso.py
- tests/unit/core/test_logger.py
- tests/unit/core/test_sdk_api.py
Support for turning loggers off
> Turning logger off

- .github/workflows/auto-comment.yml
- .github/workflows/sdk-release.yaml
- .github/workflows/update-project.yml
> Update workflow permissions (main)

- .github/workflows/auto-comment.yml
Update workflows in legacy branch
> Update workflow permissions (legacy)

- .github/dco.yml
- docs/source/usage/examples.rst
Resolves #166 
See the updated docs here: https://zowe-client-python-sdk--339.org.readthedocs.build/en/339/usage/examples.html
> Update examples.rst to add more profile options

- .github/workflows/audit.yml
- src/setup.py
- src/zos_console/setup.py
- src/zos_files/setup.py
- src/zos_jobs/setup.py
- src/zos_tso/setup.py
- src/zosmf/setup.py
> Update package author and ignore Rust advisory

- pyproject.toml
- requirements.txt
Fixes #359
for python 3.10 or higher, the `setuptools` dependency needs to be explicitly mentioned in the requirements.txt file. Also we need to add it in the build system in the `pyproject` as it's neede in the build process.
As it's a dev dependency, needed for the build process i have added it under the dev dependencies section without any version specification:
```py
setuptools
black
coverage
isort
maturin
pydoclint
pydocstyle
pyfakefs
pylint
pytest
wheel
```
All tests are observed to be passing (with 5 warnings that were already there previously).
- test output:
```sh
> src:test
> npm run src:test:pytest && npm run src:test:xml
> src:test:pytest
> coverage run -m pytest ./tests/unit
====================================================================== …
```
> fix: added missing setuptools dependency to requirements and pyproject
